version: "3.8"

services:
  # Application Service
  app:
    container_name: provider_integration
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:80"
    working_dir: /var/www/html

  #Database Service
  mysql_db:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: provider_integration
      MYSQL_ROOT_PASSWORD: password

  # phpMyAdmin Service
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql_db

  # Web Server Service
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./src:/var/www
  #     - ./nginx/conf.d/:/etc/nginx/conf.d/
  #   depends_on:
  #     - app
  #     - mysql_db
